### ISSUE TITLE
GitHub Actions: Transitioning from Node 16 to Node 20

### ISSUE THREAD

**Issue by nemuvski** [nemuvski/itsumono#27]
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, pnpm/action-setup@v2, actions/cache@v3.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by nemuvski** [comment]
- `pnpm/action-setup`
  -  https://github.com/pnpm/action-setup/issues/99 を参照

他はバージョンを1つ挙げれば良さそう。

**Comment by nemuvski** [comment]
**pnpm/action-setup@v2** に関しては

```
- run: corepack enable
- uses: actions/setup-node@v4
  with:
    node-version: 20
    cache: "pnpm"

- name: Install dependencies
  run: pnpm install
```
